channels:
- conda-forge
dependencies:
  - notebook=6.4.5
#- jupyterlab=3.2.1
#- jupyter-offlinenotebook=0.2.1
#- nbconvert=6.2.0
# Python Kernel
#- ipykernel=6.4.2
#- xeus-python=0.13.5
#- ipywidgets=7.6.3
#- ipytree=0.2.1
#- widgetsnbextension=3.5.1
#- ipyleaflet=0.14.0
#- altair=4.1
#- geopy=2.1.0
#- bqplot=0.12.20
# - metaflow
#- matplotlib=3.4.3
#- pandas=1.2.4
#- Pillow=8.2.0
  - python=3.9.7
#- pydot=1.4.2
#- qgrid=1.3.1
#- seaborn=0.11
#- sidecar=0.5.1
#  - poetry=1.1.11
#- pyyaml
#- traittypes==0.2.1
#- invoke=1.2
